name: dado
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: TaigaMikami <mikamimikami60@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
#  path: ^1.6.0
  build_cli_annotations: ^1.0.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  build_cli: ^1.0.0
  build_runner: ^1.0.0
